//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.Contacts = new HashSet<Contact>();
            this.ProfileProfessions = new HashSet<ProfileProfession>();
        }
    
        public int ProfileId { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<ProfileProfession> ProfileProfessions { get; set; }
    }
}
