//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileProfession
    {
        public int ProfileProfessionId { get; set; }
        public int ProfileId { get; set; }
        public int ProfessionId { get; set; }
    }
}
