//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetProfileDetails
    {
        public int ProfileId { get; set; }
        public string ProfileName { get; set; }
        public string ContactNumber { get; set; }
        public string Profession { get; set; }
        public string Username { get; set; }
    }
}
